pretrained_model_path: "./models/model_scope_diffusers/" #https://huggingface.co/damo-vilab/text-to-video-ms-1.7b/tree/main
output_dir: "./outputs"
train_text_encoder: False
offset_noise_strength: 0.1
use_offset_noise: True

train_data:
  json_path: "./json/train.json"
  preprocessed: True
  n_sample_frames: 1
  shuffle_frames: False
  width: 384      
  height: 320
  sample_start_idx: 0
  sample_frame_rate: 8
  vid_data_key: "video_path"

  single_video_path: ""
  single_video_prompt: ""

validation_data:
  prompt: ""
  sample_preview: True
  num_frames: 16
  width: 384
  height: 320
  num_inference_steps: 50
  guidance_scale: 9

learning_rate: 1e-5
adam_weight_decay: 1e-2
train_batch_size: 1
max_train_steps: 50000
checkpointing_steps: 2500
validation_steps: 200
unfreeze_temp: True
trainable_modules:
  - "to_q"
  - "to_k"
  - "to_v"
  - "to_out"
  - "proj_in"
  - "proj_out"

seed: 64
mixed_precision: "fp16"
use_8bit_adam: False # This seems to be incompatible at the moment. 

# Xformers must be installed
enable_xformers_memory_efficient_attention: True
