pretrained_model_path: "./text-to-video-ms-1.7b/"
output_dir: "./output"
train_text_encoder: False

train_data:
  type: folder
  path: "path/to/folder/of/videos/"
  n_sample_frames: 16
  width: 256
  height: 256
  fps: 24
  fallback_prompt: ""  # used when a video doesn't have a corresponding .txt file with a prompt

validation_data:
  prompt: ""
  sample_preview: True
  num_frames: 48
  width: 256
  height: 256
  num_inference_steps: 50
  guidance_scale: 9

learning_rate: 1e-5
adam_weight_decay: 1e-2
train_batch_size: 1
max_train_steps: 50000
checkpointing_steps: 5000
validation_steps: 500
trainable_modules:
  - "attn1"
  - "attn2"
  - "attn3"
  - "infinet"
seed: 1234
mixed_precision: "fp16"
use_8bit_adam: False # This seems to be incompatible at the moment. 
gradient_checkpointing: True
enable_xformers_memory_efficient_attention: False
enable_torch_2_attn: True
